export const NAMESPACE = "AUTH";

export const LOGIN = `${NAMESPACE}_SIGNIN`;
export const LOGIN_REQUEST_START = `${LOGIN}_REQUEST_START`;
export const LOGIN_REQUEST_SUCCESS = `${LOGIN}_REQUEST_SUCCESS`;
export const LOGIN_REQUEST_ERROR = `${LOGIN}_REQUEST_ERROR`;

export const SIGN_UP = `${NAMESPACE}_SIGN_UP`;
export const LOGINSIGN_UP_REQUEST_START = `${SIGN_UP}_REQUEST_START`;
export const LOGINSIGN_UP_REQUEST_SUCCESS = `${SIGN_UP}_REQUEST_SUCCESS`;
export const LOGINSIGN_UP_REQUEST_ERROR = `${SIGN_UP}_REQUEST_ERROR`;

export const LOGOUT = `${NAMESPACE}_LOGOUT`;
export const LOGOUT_REQUEST_START = `${LOGOUT}_REQUEST_START`;
export const LOGOUT_REQUEST_SUCCESS = `${LOGOUT}_REQUEST_SUCCESS`;
export const LOGOUT_REQUEST_ERROR = `${LOGOUT}_REQUEST_ERROR`;