export const NAMESPACE = "COMPETITORS";

export const INDEX = `${NAMESPACE}_INDEX`;
export const INDEX_REQUEST_START = `${INDEX}_REQUEST_START`;
export const INDEX_REQUEST_SUCCESS = `${INDEX}_REQUEST_SUCCESS`;
export const INDEX_REQUEST_ERROR = `${INDEX}_REQUEST_ERROR`;

export const LOAD = `${NAMESPACE}_LOAD`;
export const LOADSIGN_UP_REQUEST_START = `${LOAD}_REQUEST_START`;
export const LOADSIGN_UP_REQUEST_SUCCESS = `${LOAD}_REQUEST_SUCCESS`;
export const LOADSIGN_UP_REQUEST_ERROR = `${LOAD}_REQUEST_ERROR`;

export const UPDATE = `${NAMESPACE}_UPDATE`;
export const UPDATE_REQUEST_START = `${UPDATE}_REQUEST_START`;
export const UPDATE_REQUEST_SUCCESS = `${UPDATE}_REQUEST_SUCCESS`;
export const UPDATE_REQUEST_ERROR = `${UPDATE}_REQUEST_ERROR`;

export const REMOVE = `${NAMESPACE}_REMOVE`;
export const REMOVE_REQUEST_START = `${REMOVE}_REQUEST_START`;
export const REMOVE_REQUEST_SUCCESS = `${REMOVE}_REQUEST_SUCCESS`;
export const REMOVE_REQUEST_ERROR = `${REMOVE}_REQUEST_ERROR`;

export const ADD = `${NAMESPACE}_ADD`;
export const ADD_REQUEST_START = `${ADD}_REQUEST_START`;
export const ADD_REQUEST_SUCCESS = `${ADD}_REQUEST_SUCCESS`;
export const ADD_REQUEST_ERROR = `${ADD}_REQUEST_ERROR`;